module.exports = {'data': [ 
  { url: 'http://www.nytimes.com/interactive/2016/us/elections/primary-calendar-and-results.html',
    byline: 'By WILSON ANDREWS, KITTY BENNETT and ALICIA PARLAPIANO',
    abstract: 'The 2016 primaries and caucuses have begun. See results and upcoming primary dates.',
    headline: '2016 Primary Results and Calendar',
    date: '2016-03-08',
    articleId: 100000003627564,
    img: 
     { url: 'http://static01.nyt.com/images/2015/04/14/us/elections/primary-calendar-and-results-1429026715315/primary-calendar-and-results-1429026715315-superJumbo-v8.png',
       format: 'superJumbo',
       height: 704,
       width: 940 } },
  { url: 'http://www.nytimes.com/2016/03/08/us/politics/michael-bloomberg-not-running-for-president.html',
    byline: 'By MAGGIE HABERMAN and ALEXANDER BURNS',
    abstract: 'In bowing out, Mr. Bloomberg cited his fear that a three-way race could lead to the election of Donald J. Trump.',
    headline: 'Michael Bloomberg Says He Won’t Run for President',
    date: '2016-03-08',
    articleId: 100000004257123,
    img: 
     { url: 'http://static01.nyt.com/images/2016/03/08/us/08BLOOMBERG/08BLOOMBERG-superJumbo.jpg',
       format: 'superJumbo',
       height: 1366,
       width: 2048 } },
  { url: 'http://www.nytimes.com/2016/03/08/opinion/its-not-too-late.html',
    byline: 'By DAVID BROOKS',
    abstract: 'Republicans still have time to reject Donald Trump, avoid Ted Cruz and pick a nominee who allows them to maintain their standards.',
    headline: 'It’s Not Too Late!',
    date: '2016-03-08',
    articleId: 100000004257168,
    img: 
     { url: 'http://static01.nyt.com/images/2014/11/01/opinion/brooks-circular/brooks-circular-superJumbo-v2.png',
       format: 'superJumbo',
       height: 228,
       width: 228 } },
  { url: 'http://www.nytimes.com/2016/03/08/sports/tennis/maria-sharapova-failed-drug-test.html',
    byline: 'By CHRISTOPHER CLAREY and MIKE TIERNEY',
    abstract: 'Sharapova, who has battled injuries in recent years, said that at the Australian Open, she tested positive for the drug meldonium, which aids oxygen flow.',
    headline: 'Maria Sharapova Admits Taking Meldonium, Drug Newly Banned by Tennis',
    date: '2016-03-08',
    articleId: 100000004256561,
    img: 
     { url: 'http://static01.nyt.com/images/2016/03/08/sports/08SHARAPOVAvideo/08SHARAPOVAvideo-superJumbo.jpg',
       format: 'superJumbo',
       height: 1449,
       width: 2048 } },
  { url: 'http://www.nytimes.com/2016/03/09/us/politics/primary-elections-preview.html',
    byline: 'By NATE COHN and JONATHAN MARTIN',
    abstract: 'Is Donald J. Trump fading? Will Senator Marco Rubio continue his recent slide? These and other questions will be answered as voters in Hawaii, Idaho, Michigan and Mississippi have their say.',
    headline: 'What We’re Watching as 4 States Vote and Both Parties Court Michigan',
    date: '2016-03-09',
    articleId: 100000004257860,
    img: 
     { url: 'http://static01.nyt.com/images/2016/03/09/us/elections/09elect1_hp/09elect1_hp-superJumbo.jpg',
       format: 'superJumbo',
       height: 1365,
       width: 2048 } },
  { url: 'http://well.blogs.nytimes.com/2016/03/07/intermittent-fasting-diets-are-gaining-acceptance/',
    byline: 'By ANAHAD O\'CONNOR',
    abstract: 'The health benefits of skipping meals are growing more apparent, though critics argue that the idea is still impractical for most people.',
    headline: 'Fasting Diets Are Gaining Acceptance',
    date: '2016-03-07',
    articleId: 24,
    img: 
     { url: 'http://static01.nyt.com/images/2016/03/08/science/08FASTINGCOVER/08FASTINGCOVER-superJumbo.jpg',
       format: 'superJumbo',
       height: 2048,
       width: 1465 } },
  { url: 'http://www.nytimes.com/2016/03/08/us/trumps-rise-spurs-latino-immigrants-to-naturalize-to-vote-against-him.html',
    byline: 'By JULIA PRESTON',
    abstract: 'Mr. Trump’s harsh language against Mexican immigrants has compelled legal residents to seek citizenship in time to vote against him in November.',
    headline: 'More Latinos Seek Citizenship to Vote Against Trump',
    date: '2016-03-08',
    articleId: 100000004249632,
    img: 
     { url: 'http://static01.nyt.com/images/2016/03/04/us/00naturalize-web01/00naturalize-web01-superJumbo.jpg',
       format: 'superJumbo',
       height: 1363,
       width: 2048 } },
  { url: 'http://www.nytimes.com/2016/03/08/opinion/an-anti-semitism-of-the-left.html',
    byline: 'By ROGER COHEN',
    abstract: 'Overheard at Oberlin: The Holocaust was mere "white on white crime."',
    headline: 'An Anti-Semitism of the Left',
    date: '2016-03-08',
    articleId: 100000004255919,
    img: 
     { url: 'http://static01.nyt.com/images/2014/11/01/opinion/cohen-circular/cohen-circular-superJumbo-v2.png',
       format: 'superJumbo',
       height: 228,
       width: 228 } },
  { url: 'http://www.nytimes.com/2016/03/08/opinion/campaign-stops/the-presidential-plot-thickens.html',
    byline: 'By ARTHUR C. BROOKS and GAIL COLLINS',
    abstract: 'Arthur C. Brooks and Gail Collins on the rise of Cruz, the fall of Rubio, the persistence of Trump and the triumph of Don Rickles.',
    headline: 'The Presidential Plot Thickens',
    date: '2016-03-08',
    articleId: 100000004257973,
    img: 
     { url: 'http://static01.nyt.com/images/2016/03/08/opinion/08conversationWeb/08conversationWeb-superJumbo.jpg',
       format: 'superJumbo',
       height: 1410,
       width: 2048 } },
  { url: 'http://www.nytimes.com/2016/03/08/world/asia/china-woman-elevator-death.html',
    byline: 'By CHRIS BUCKLEY',
    abstract: 'People expressed anger that lax building management could turn trivial acts, like riding an elevator, into fatal traps, news reports and Internet accounts said.',
    headline: 'Death of Chinese Woman Trapped in Elevator for Month Stokes Uproar',
    date: '2016-03-08',
    articleId: 100000004255789,
    img: 
     { url: 'http://www.trbimg.com/img-56b0e859/turbine/la-na-inside-iowa-caucus-precinct-20160202',
       width: 2048,
       height: 1162 } },
  { url: 'http://www.nytimes.com/2016/03/09/us/politics/fox-news-democratic-candidates.html',
    byline: 'By NICK CORASANITI',
    abstract: 'Hillary Clinton and Bernie Sanders appeared together on the channel, which has not hosted a presidential campaign event with all the Democratic candidates since 2004.',
    headline: 'Fox News Forum May Signal Thaw Between Democrats and Network',
    date: '2016-03-09',
    articleId: 100000004258124,
    img: 
     { url: 'http://static01.nyt.com/images/2016/03/09/us/09foxdems/09foxdems-superJumbo.jpg',
       format: 'superJumbo',
       height: 1365,
       width: 2048 } },
  { url: 'http://www.nytimes.com/2016/03/08/arts/television/downton-abbey-season-6-finale-review.html',
    byline: 'By MIKE HALE',
    abstract: 'This show, with its six seasons and immense popularity, has taught us about our television viewing habits.',
    headline: '‘Downton Abbey’: Lessons Learned After Six Seasons',
    date: '2016-03-08',
    articleId: 100000004253932,
    img: 
     { url: 'http://static01.nyt.com/images/2016/03/04/arts/04DOWNTON3/04DOWNTON3-superJumbo.jpg',
       format: 'superJumbo',
       height: 1271,
       width: 2048 } },
  { url: 'http://www.nytimes.com/2016/03/08/business/media/erin-andrews-awarded-55-million-in-lawsuit-over-nude-video-at-hotel.html',
    byline: 'By DANIEL VICTOR',
    abstract: 'The Fox sportscaster had sued for $75 million for negligence after a stalker secretly filmed her naked through a peephole at the Nashville Marriott.',
    headline: 'Erin Andrews Awarded $55 Million in Lawsuit Over Nude Video at Hotel',
    date: '2016-03-08',
    articleId: 100000004257706,
    img: 
     { url: 'http://static01.nyt.com/images/2016/03/08/us/08xp-andrews-1/08xp-andrews-1-superJumbo.jpg',
       format: 'superJumbo',
       height: 1571,
       width: 2048 } },
  { url: 'http://www.nytimes.com/2016/03/08/nyregion/elizabeth-garrett-first-female-president-of-cornell-dies-at-52.html',
    byline: 'By DANIEL E. SLOTNIK',
    abstract: 'Ms. Garrett, who started the position last summer, announced a month ago that she had learned she had colon cancer.',
    headline: 'Elizabeth Garrett, First Female President of Cornell, Dies at 52',
    date: '2016-03-08',
    articleId: 100000004256769,
    img: 
     { url: 'http://static01.nyt.com/images/2016/03/08/nyregion/08-Garrett-Obit-WEB/08-Garrett-Obit-WEB-superJumbo-v2.jpg',
       format: 'superJumbo',
       height: 750,
       width: 1125 } },
  { url: 'http://www.nytimes.com/2016/03/08/business/international/unease-after-trump-depicts-tokyo-as-an-economic-rival.html',
    byline: 'By JONATHAN SOBLE and KEITH BRADSHER',
    abstract: 'In an attack reminiscent of another era, Mr. Trump has chastised Japan as a country where “we are getting absolutely crushed on trade.”',
    headline: 'Donald Trump Laces Into Japan With a Trade Tirade From the ’80s',
    date: '2016-03-08',
    articleId: 100000004252603,
    img: 
     { url: 'http://static01.nyt.com/images/2016/03/08/business/08TRUMPJAPAN1/08TRUMPJAPAN1-superJumbo.jpg',
       format: 'superJumbo',
       height: 2008,
       width: 1709 } },
  { url: 'http://www.nytimes.com/2016/03/08/us/politics/netanyahu-calls-off-washington-visit-and-fingers-point.html',
    byline: 'By JULIE HIRSCHFELD DAVIS',
    abstract: 'The Israeli prime minister abruptly canceled a trip to Washington that was to include a visit with President Obama, prompting speculation that a rift between two leaders lingers.',
    headline: 'Netanyahu Calls Off Obama Visit, and Fingers Point',
    date: '2016-03-08',
    articleId: 100000004257807,
    img: 
     { url: 'http://www.trbimg.com/img-56b0e859/turbine/la-na-inside-iowa-caucus-precinct-20160202',
       width: 2048,
       height: 1162 } },
  { url: 'http://www.nytimes.com/2016/03/08/world/africa/us-airstrikes-somalia.html',
    byline: 'By HELENE COOPER',
    abstract: 'The strikes hit a camp where officials said fighters with the Shabab militant group were preparing an attack against American troops and their allies.',
    headline: 'U.S. Strikes in Somalia Kill 150 Shabab Fighters',
    date: '2016-03-08',
    articleId: 100000004256605,
    img: 
     { url: 'http://static01.nyt.com/images/2016/03/07/world/africa/attack-map-1457382251994/attack-map-1457382251994-superJumbo.png',
       format: 'superJumbo',
       height: 2048,
       width: 1844 } },
  { url: 'http://www.nytimes.com/interactive/2016/03/07/us/politics/document-Bloomberg.html',
    byline: '',
    abstract: 'The maps that Michael R. Bloomberg\'s aides used internally to guide their thinking about how he would affect the presidential race.',
    headline: 'Maps Show Where Bloomberg Aides Thought He Would Be Competitive',
    date: '2016-03-07',
    articleId: 100000004257488,
    img: 
     { url: 'http://static01.nyt.com/images/2016/03/08/us/politics/08bloomberg-doc/08bloomberg-doc-superJumbo.png',
       format: 'superJumbo',
       height: 446,
       width: 657 } },
  { url: 'http://www.nytimes.com/2016/03/09/technology/in-san-francisco-and-rooting-for-a-tech-slowdown.html',
    byline: 'By DAVID STREITFELD',
    abstract: 'The city is bulging, the rents soaring, and residents are growing more vocal about wishing Silicon Valley would cool off, or at least pay up.',
    headline: 'In San Francisco and Rooting for a Tech Comeuppance',
    date: '2016-03-09',
    articleId: 100000004218458,
    img: 
     { url: 'http://static01.nyt.com/images/2016/03/05/business/07fallout1/06fallout1-superJumbo.jpg',
       format: 'superJumbo',
       height: 1365,
       width: 2048 } },
  { url: 'http://www.nytimes.com/2016/03/08/us/prayer-dispute-between-somalis-and-plant-reshapes-a-colorado-town-again.html',
    byline: 'By JULIE TURKEWITZ',
    abstract: 'The conflict offers a case study on what happens when matters of religious accommodation knock heads with the demands of the American assembly line.',
    headline: 'Prayer Dispute Between Somalis and Plant Reshapes a Colorado Town, Again',
    date: '2016-03-08',
    articleId: 100000004251445,
    img: 
     { url: 'http://static01.nyt.com/images/2016/03/06/us/00fortmorgan-web04/00fortmorgan-web04-superJumbo.jpg',
       format: 'superJumbo',
       height: 1357,
       width: 2048 } } 
]}